### ISSUE TITLE
Milestone report: Include observations

### ISSUE THREAD

**Issue by jajimentol** [CAKES-coding/swe574-group2#100]
Milestone report shall include observation part, which;
- elaborates on the workflow for the milestone
- elaborates on the differences comparing other milestones
- explains any observation made my a team member.

**Comment by active-sludge** [comment]
Finished the report. 
Please check it out:
https://github.com/CAKES-coding/swe574-group2/wiki/Milestone-Report-2-(06.12.2021)

**Comment by jajimentol** [comment]
[#64-Activity Manager](https://github.com/CAKES-coding/swe574-group2/issues/64) issue eklenebilir, onu da kapattık.

A workflow description could be added, or issues could be ordered by chronological order, might be good to add the dates as well.

Rest seems all good. GJ!

**Comment by active-sludge** [comment]
I did not include #64 because it's an issue of the next milestone. We can show it at the next one.
Ordered issue chronologically.
Added a Gantt chart of this milestone.

Check it out:
https://github.com/CAKES-coding/swe574-group2/wiki/Milestone-Report-2-(06.12.2021)

**Comment by jajimentol** [comment]
Alrighty.
