### ISSUE TITLE
Author identifier causes fetchArticles to save duplicate author

### ISSUE THREAD

**Issue by semihsolmaz** [CAKES-coding/swe574-group2#105]
**Describe the bug**
Author identifier causes fetchArticles to save duplicate author
**To Reproduce**
1. Go to 'get articlets'
2. Enter 'lupus' for Topic
3. Enter '2000' for number of articles
4. Click 'Submit'
5. Wait until a error

**Expected behavior**
Articles needs to be saved without exception

**Additional context**
Some authors are given with identifier in one article while same author is given without identifier in another article get_or_create treats them as different authors if identifier is given.

**Comment by semihsolmaz** [comment]
etkilediği için bu PR'ın içinde fixledim.

**Comment by active-sludge** [comment]
Eline saglik Semih 👍
