### ISSUE TITLE
Upvote/Downvote tag

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#114]
**Is your feature request related to a problem? Please describe.**
We want upvoted tags will be suggested more. 

**Describe the solution you'd like**
Upvote and downvote buttons will increase or decrease a tag's point.

**Comment by kenankural** [comment]
We will create a seperate model to save the upvote/downvote.
New model will have one-to-many relationship with Tagreation Model
In this new model there will be;
- userID
- TagID
- Upvote/Downvote

columns.
