### ISSUE TITLE
Rank semantic search results

### ISSUE THREAD

**Issue by emrecalik** [CAKES-coding/swe574-group2#116]
**Describe the solution you'd like**
Fetched results will be ranked according to ranking rules.

Priorities:
1. Article Title
2. Article Tag
3. Parent & Child Tag
4. Article Abstract

**Comment by semihsolmaz** [comment]
This issue is related to https://github.com/CAKES-coding/swe574-group2/issues/115
It is resolved in same PR https://github.com/CAKES-coding/swe574-group2/pull/177
