### ISSUE TITLE
Tagged articles on profile

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#117]
**Describe the solution you'd like**
We want to see tagged articles on the profile page.

There are two tabs on the profile page. Tagged articles and Recent activities. They are filled with mock data.
Tagged articles of users shall be shown on the user's profile page.

**Comment by kenankural** [comment]
I could not understand this issue clearly, do we want to show tagged articles of users in the home page ? It is written here that tagged articles of users shall be shown on user's profile page but it is already in there ? @active-sludge do you have any comment ?

**Comment by active-sludge** [comment]
@kenankural The tagged articles on the profile page are dummy data. They are hard-coded article names to just fill the tab.

**Comment by kenankural** [comment]
In profile page, we will replace mock data with real data for tagged articles.

**Comment by kenankural** [comment]
Done
