### ISSUE TITLE
Recent activities on profile page

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#118]
**Describe the solution you'd like**
The activity manager is ready. Activities can be stored. 
Now we want to see the last five (recent) activities to be shown.

Examples:
- Emre tagged Mechanisms of SARS-CoV-2 Transmission and Pathogenesis.moments ago
- Emre voted for Pregnancy and Birth Outcomes during the Early Months of the COVID-19 Pandemic: The MOACC-19 Cohort.7 minutes ago
- Emre updated Susceptibility and Attenuated Transmissibility of SARS-CoV-2 in Domestic Cats.3 days ago
- Emre is followed by Can.1 month ago
- Emre followed Semih.

**Comment by kenankural** [comment]
Currently, the front end version of this issue is ready but it doesnt take the activities from activity manager. Let's talk this issue tomorrow, then I will develop the backend as well.

**Comment by kenankural** [comment]
In profile page, user's activities and in home page, everyone's activities will be shown with real data. Discussed in Saturday meeting (12.12.2021)

**Comment by kenankural** [comment]
Also recent activities on home page will be updated.
