### ISSUE TITLE
Recommend an article to the user

### ISSUE THREAD

**Issue by jajimentol** [CAKES-coding/swe574-group2#124]
Users shall get article recommendations based on;
- Followed users
- Viewed articles
- Tagged articles

Viewed articles shall not be recommended for 1 week.
A new recommendation shall be advised every 24 hours.

**Comment by active-sludge** [comment]
I would like to see a **Viewed** article from a **User** I follow.

**Comment by kenankural** [comment]
I would like to see the most viewed article in the last 7 days.

**Comment by emrecalik** [comment]
I would like to see articles tagged by people who i follow.

**Comment by jajimentol** [comment]
I would like to see a recently tagged article.

**Comment by semihsolmaz** [comment]
I would like to see an article with a tag I used for another article. (I used tag A, it will suggest other articles that already have tag A)
