### ISSUE TITLE
Recommend a user to the user

### ISSUE THREAD

**Issue by jajimentol** [CAKES-coding/swe574-group2#126]
Users shall get user recommendations depending on;
- Followed users
- Article views
- Tag usages

Viewed users shall not be recommended for 1 week.
A new recommendation shall be advised every 24 hours.

**Comment by active-sludge** [comment]
I would like to see a **User** followed by a **User** that I follow.
Me >follow> User-1 >follow> User-2
User-2 >suggested> me

**Comment by kenankural** [comment]
I would like to see the **_users who follows me but I do not follow them_** in user suggestions section.

**Comment by emrecalik** [comment]
I would like to see the most followed users.

**Comment by jajimentol** [comment]
I would like to see a user who viewed the same article as I viewed.

**Comment by semihsolmaz** [comment]
I would like to see a user who tagged the article I have tagged/viewed.
