### ISSUE TITLE
Milestone report 13.12.2021

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#128]
Prepare the milestone report for the last week.
https://github.com/CAKES-coding/swe574-group2/wiki/Milestone-Report-3-(13.12.2021)

**Comment by kenankural** [comment]
@active-sludge geçen hafta yaptığımız gibi, yarın 6 da buluşup raporun üzerinden geçebiliriz, senin için de uygunsa.

**Comment by active-sludge** [comment]
Rapor hazir. Yukaridaki linkten ulasilabilir.
