### ISSUE TITLE
Target on activities are always redirecting to article page.

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#144]
**Describe the bug**
On recent activities, 'kenan2 followed kenan2'activity, second activity is redirecting to an article with the same id.

**To Reproduce**
1. Sign in
2. Go to 'Homepage'
3. Click on the second name on a following activity. Example 'can followed **kenan2**.'
4. Redirect to an article.

**Expected behavior**
It should go to kenan2's profile.

**Comment by semihsolmaz** [comment]
PR: https://github.com/CAKES-coding/swe574-group2/pull/146
viewdeki kodu utils altına taşıdım, Activity querySet alıp feed itemlardan olusan bir list of dict dönüyor.
template üzerinde Feed classına göre düzenleme yaptım.
