### ISSUE TITLE
Tag activity saves tag URL with article ID

### ISSUE THREAD

**Issue by semihsolmaz** [CAKES-coding/swe574-group2#145]
``**Describe the bug**
When an article is tagged, related activity's object target shows a tag URL wşth article ID

**To Reproduce**
1. Go to a article
2. Tag the article
3. View activity of tagging

**Expected behavior**
Activity should show the related tags ID and URL

**Additional context**
``` json
{
    "tag": {
        "id": "http://www.wikode.com/wikode/tag/9"
    },
    "type": "Add",
    "actor": {
        "id": "http://www.wikode.com/wikode/profile/1",
        "url": "http://www.wikode.com/wikode/profile/1",
        "name": "admin",
        "type": "Person"
    },
    "object": {
        "id": "http://www.wikode.com/wikode/tag/245", -> this id belongs to article tag is tagged not the tag itself
        "url": "http://www.wikode.com/wikode/tag/245",
        "name": "Tumid lupus erythematosus and systemic lupus erythematosus: a rare coexistence.",
        "type": "Article"
    },
    "summary": "admin tagged Tumid lupus erythematosus and systemic lupus erythematosus: a rare coexistence.",
    "@context": "https://www.w3.org/ns/activitystreams",
    "published": "2021-12-14T23:58:47.247296"
}
```

**Comment by kenankural** [comment]
Article' a gitmeyecek zaten ama tag diye bir sayfa yok, düzeltebiliriz.

**Comment by jajimentol** [comment]
this means:

actor adds tag to object

we need a /tag/{id} page

**Comment by semihsolmaz** [comment]
https://github.com/CAKES-coding/swe574-group2/pull/187

Orada kullandıgımız add type'ı bizim senaryomuzu karsılamıyor tam olarak. Onun yerine object'i bizim article page olacak sekilde JSON yapısını degistirdim.
