### ISSUE TITLE
Integrate CI/CD with GitHub action

### ISSUE THREAD

**Issue by emrecalik** [CAKES-coding/swe574-group2#15]

**Comment by jajimentol** [comment]
Github actions'dan bir workflow oluşturdum. Şu anda çalışmayacak çünkü deploy edilecek bir makine yok. Repo settings -> Actions kısmına resimdekileri eklediğimiz zaman çalışacaktır. Çalışma şekli şu şekilde;

- önce checkout yapıyor
- sonra verdiğimiz credentials ile dockerHub'a giriş yapıyor
- docker buildx kuruyor
- docker imajı pulluyor
- docker-compose-up ile son hali makinaya kuruyor.

**Comment by jajimentol** [comment]
A Dockerfile needs to be integrated to project. Until then, this isssue is hold.

**Comment by semihsolmaz** [comment]
https://github.com/CAKES-coding/swe574-group2/issues/33#issuecomment-960241244 burada çözülmüş oldu bu da.

**Comment by jajimentol** [comment]
@semihsolmaz eline sağlık abi çalışıyor bir sıkıntı çıkmadı.
Issue closed.
