### ISSUE TITLE
When tagging with wikidata tagging area comes at the end of the page

### ISSUE THREAD

**Issue by kenankural** [CAKES-coding/swe574-group2#174]
**Describe the bug**
When a user try to tag an article with wikidata url, tagging window comes at the end of the page, user might think that it does not work. 

**To Reproduce**
1. Go to an article
2. Click on tag with wikidataurl
3. Scroll down to tagging window

**Expected behavior**
When user wants to tag with wikidata, tagging window should automatically come.

**Comment by semihsolmaz** [comment]
Wikidata formunu sag altta pop up olacak sekilde tasıdım 

@kenankural 

https://github.com/CAKES-coding/swe574-group2/pull/186
