### ISSUE TITLE
Do not show tag list on article detail if article isnot tagged

### ISSUE THREAD

**Issue by semihsolmaz** [CAKES-coding/swe574-group2#176]
**Describe the bug**
An empty list covers a lot of space on article detail screen while there is not tag to display for the article.

**To Reproduce**
1. Go to a article with out any tag.
2. Scroll down to Tag list
3. See empty tag list

**Expected behavior**
List div shpuld be hidden in case there is no tag related to article.

**Screenshots**
![image](https://user-images.githubusercontent.com/25771247/147890463-04a9cb22-6c7b-4fb4-a3d2-dbcb28c76155.png)

**Comment by jajimentol** [comment]
#185 Pr opened
