### ISSUE TITLE
Non-member test

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#178]
Invite someone who is not from this team to test the app.
Record the findings and bugs.

**Comment by active-sludge** [comment]
Credentials:
username: can@dayan.com
password: L36EXUQN

Test case scenario:
| # | Step                                      | Expected Behaviour   | Actual Behaviour |
|---|-------------------------------------------|----------------------|------------------|
| 1 | Enter the url.                            | Login page is shown. |                  |
| 2 | Enter username and password. Click login. |                      |                  |
| 3 | Last issue merged on                      |                      |                  |
| 4 |                                           |                      |                  |
| 5 |                                           |                      |                  |
| 6 |                                           |                      |                  |

**Comment by emrecalik** [comment]
Scenarios were tested with Ulaş Dedeoğlu at 05/01/2022. All tests were passed successfully. However, Ulaş had several comments:

- It might be better not to show activities of logged-in user.
- Start & end date features on filters section on homepage are not formatted before doing any search.
- Time information for activities are not shown for local time.
