### ISSUE TITLE
Prepare the sequence diagrams for scenarios

### ISSUE THREAD

**Issue by jajimentol** [CAKES-coding/swe574-group2#27]
Gather the ideas for sequence diagrams to 25.10.2021 Saturday meeting.

**Comment by jajimentol** [comment]
1- Filter and search feature
2- Partial tagging feature
3- Suggestion feature

Sequences are decided.

**Comment by jajimentol** [comment]
@active-sludge please add sequence wiki link to this.

**Comment by active-sludge** [comment]
Sequence diagrams are added.
https://github.com/CAKES-coding/swe574-group2/wiki/Sequence-Diagram

@emrecalik Please also include the sequence diagram to the home page. #34
