### ISSUE TITLE
Add Dockerfile to the project

### ISSUE THREAD

**Issue by jajimentol** [CAKES-coding/swe574-group2#33]
Dockerfile needs to be implemented including requirements for;
- CI purposes
- Team members' local setup

**Comment by semihsolmaz** [comment]
Docker file added on develop branch

https://github.com/CAKES-coding/swe574-group2/blob/develop/Project/Wikode/Dockerfile

**Comment by jajimentol** [comment]
@active-sludge @semihsolmaz maine alabilir miyiz bunu acaba uygund mudur?

**Comment by active-sludge** [comment]
@semihsolmaz review'den geçirdkten sonra ben alırım hemen main'e.

**Comment by semihsolmaz** [comment]
alabiliriz zaten temel seyler su an içindekiler python kurup dosyları tasıyor o kadar
directory isimlerini değiştirdim şimdi, main'e alabiliriz

**Comment by active-sludge** [comment]
@jajimentol 
develop, main'e merge edildi.

**Comment by jajimentol** [comment]
build on dockerHub gives an err
<img width="1289" alt="Ekran Resmi 2021-11-01 13 32 12" src="https://user-images.githubusercontent.com/6799302/139658508-56c6a97c-354f-4a25-9a4d-6917e211538a.png">
or

**Comment by jajimentol** [comment]
Mac localde çalışıtırınca da böyle bir hata oluyor, ilgili olabilir
![WhatsApp Image 2021-11-01 at 13 21 33](https://user-images.githubusercontent.com/6799302/139658977-10164859-6233-4001-92a9-977c99a29b73.jpeg)

**Comment by active-sludge** [comment]
@jajimentol 
Bizim mac'lerde bu hatayı alma sebebimiz dependency'i binary hali ile yüklememiz gerektiği. Yani şu isimle: `psycopg2-binary`
Aşağıdaki linkte de açıklamalar verilmiş.
https://stackoverflow.com/questions/49811955/unable-to-install-psycopg2-pip-install-psycopg2

Semih'in söylediğine göre bu hata linux'ta gerçekleşmiyor.

Kendi local'inde bir linux VM oluşturarak yüklemeyi deneyebilirsin. O zaman konsolda yazan hatayı direkt görebilirsin belki.

**Comment by semihsolmaz** [comment]
Aşağıdaki adımları gerçekleştirerek workflow'u düzenledim, yukarıdaki hata giderildikten sonra da bazı değişiklikler gerekti:

1.  workflow main.yml içinde docker file ve project folder directory adresleri değiştirildi.
2. vm ssh key formatı rsa dan openSSH a cevirildi
3. hedef makineye docker-compose kuruldu, registry_user için yetkilendirme yapıldı
4. django allowed hostlar güncellendi (allow all dedim duruma göre değiştiriz)
5. hedef makine docker yetkilendirmeleri registry_user için düzenlendi
6. docker-compose dosyası oluşturuldu hedef makineye aktarıldı (/some/registry_user/docker-compose.yml)
7. hedef makine network ayarları 800 portunu dinleyecek şekilde düzenlendi

ayrıca workflow'a manual trigger ekledim, kaldırıabilir ama şimdilik dursun develeopment sırasında gerek duyabiliriz.

Şu an azure'da django çalışıyor ama içi boş login ve register için PR açtım o versiyonu main'e ilerlettiğimizde login ekranının gelmesi gerekli.

ortamın adresi:
http://20.56.24.44:8000/

**Comment by semihsolmaz** [comment]
@jajimentol kontrol edebilirsin.

**Comment by jajimentol** [comment]
@semihsolmaz @active-sludge düzeltmeler çalışıyor, CI tarafı da düzeldi. Bu issue yu da kapatabiliriz.
