### ISSUE TITLE
Add ss and gifs to Mockups wiki

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#40]
Guys,
We have prepared mockups #26. Let's showcase them on the Mockups wiki page.

1. Make sure the image/gif has at least 800 px width for the optimum resolution.
2. Add your images/gifs to the [external_resources/Mockups](https://github.com/CAKES-coding/swe574-group2/tree/develop/external_resources/Mockups)  folder. Commit, Push, Open PR (no need to add reviewer), Merge.
3. Add their links to the [Mockups](https://github.com/CAKES-coding/swe574-group2/wiki/Mockups) wiki page.
4. Use below HTML tag to add image/gif. Give 800 as width.
`<img src="https://raw.githubusercontent.com/CAKES-coding/swe574-group2/develop/external_resources/Mockups/UpvoteDownvoteTag.gif" width="800"> `

Check out how I did min on the wiki page.

**Comment by kenankural** [comment]
Gif added for scenario-4 by following the procedure stated.
