### ISSUE TITLE
Revise all the sequence diagrams

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#42]
Revise all the sequence diagrams considering the professor's last comments. Below are some of the marks:
 
- Variable names of parameters and return values must be accurate.
- Add database relationship with Models.
- If there is a loop, annotate it.
- Make it detailed as much as you can. Because we will start coding using the diagram.
- Give design decisions when necessary. If not sure, still make a decision and open discussion afterward.

You can find the raw diagram files inside the shared google drive folder SWE 574.
Don't hesitate to ask someone to assist you.

**Comment by active-sludge** [comment]
- Database en saga modul olarak eklenecek.
- return'ler gozukecek

**Comment by kenankural** [comment]
Değişiklikleri tamamladım, kontrol edebilir misin @active-sludge

**Comment by active-sludge** [comment]
Kenan eline sağlık. İki madde gözüme takıldı, aşağıda yazdım

**Article search and filter:**
- [ ] searched_keywords argümanları searchForm olarak değişmeli.
- [ ] generateSearchQuery metodundan dönen "Filter" değişkeni var, bu da filterConditions olarak değişmeli.

**Comment by kenankural** [comment]
Thanks for the feedbacks Can, I have updated the diagrams considering your feedbacks. Could you check again ?

**Comment by active-sludge** [comment]
eline sağlık abi.
