### ISSUE TITLE
Enhance PR procedure

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#43]
Add details about what is going to be reviewed in the PR process.
This will be our Pull Request Reviewing Procedure. We will reference it.

- Add when to ask for resolve, when to reject a PR, when to accept a PR.
- Add some tips on how to make a helpful comment.
- Spare no detail.
- Some starter rules could be:
  - Duplicate code should be removed. 
  - PR scope is too broad. Divide some of the code into another branch and another PR.
  - Unit tests should cover added functionality.

Remember what we discussed at the last meeting.

**Comment by jajimentol** [comment]
[PR Procedure](https://github.com/CAKES-coding/swe574-group2/wiki/Pull-Request-Procedure) expanded.
Coder, reviewer sides added with descriptions and examples.

**Comment by active-sludge** [comment]
Bir iki ufak typo gördüm, düzelttim.
Ellerine sağlık, gayet güzel olmuş.
