### ISSUE TITLE
Setup the code base

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#44]
Once we are ready to start coding. We need to have clean a codebase to build on.

From your SWE573 gather every single useful class, method, manager, model, and etc. 
Include frontend files.
Ensure that it is building and functional, as it's presented as SWE 573 final project.
No need to be picky, or perfectionist. 

Bonus: Refactor the code if you can.

The end goal is to have a functional SWE 573 project. Once we are sure that we have it, we can build on it.

**Comment by semihsolmaz** [comment]
Bunu oarça parça taşıyorum kontrollü olarak gitmek adına:

Aşağıdaki şekilde taşıyacağım, bitenler işaretli ve PR'ları linkli:

- [ ] [login and registration](https://github.com/CAKES-coding/swe574-group2/pull/52)
- [ ] home page and basic search
- [ ] article detail
- [ ] tagging and tag screens

**Comment by active-sludge** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/58622770/140606013-c3c87987-be02-4135-9f4d-bbd4f0ff27c0.png">

Tag eklenirken oneri gosterecek sekilde feature da eklenecek.

**Comment by semihsolmaz** [comment]
finished carrying with this https://github.com/CAKES-coding/swe574-group2/pull/71

**Comment by emrecalik** [comment]
Denedim, çalışıyor. Eline sağlık @semihsolmaz.
