### ISSUE TITLE
Create a draft ghant chart

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#45]
This will be our base for the ultimate Ghant chart. 
It's important to stick to the schedule.
And this will be used to open issues for the backlog.

Detail the issues to the simplest modules.

**Comment by active-sludge** [comment]
@jajimentol 
Aşağıdaki gibi üzerine tartışabileceğimiz bir ghant chart oluşturdum. 
https://github.com/CAKES-coding/swe574-group2/wiki/Project-Ghant-Chart

**Comment by active-sludge** [comment]
@kenankural Aşağıdaki şekilde düzenledim.
https://github.com/CAKES-coding/swe574-group2/wiki/Project-Gantt-Chart

**Comment by kenankural** [comment]
Eline sağlık @active-sludge cumartesi günü yaptığımız toplantıda konuştuğumuz gibi user profile tarafını aşağılara alalım mı ? Yoksa bu şekilde mi kalsın ? Sonuçta bir çok farklı noktaya dokunuyor zaten. Ne dersin ?
