### ISSUE TITLE
Make scenarios more specific

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#46]
As per the last comments, some of our scenarios are lacking specifics.

Scan all the scenarios and make them more specific.
- Don't let any ambiguous statement slip.
- Use statements like, "Cenk types “diabetics” on the search bar to search for articles".
- You can consider narrowing them to be more atomic.

This issue is related to the #47 Update the mockups.
You will update the mockups, based on these scenarios. Mockups should. show the exact scenario.

[Scenario 4](https://github.com/CAKES-coding/swe574-group2/wiki/Scenarios#scenario-4-cenk-search-for-article-and-filter-in-detail) is a good example to get going.

**Comment by active-sludge** [comment]
- [ ] Senaryo 2'de bir revizyon gerekecek. 

Scenario 2'de bir karışıklık var gibi. Geçen hafta hoca demişti ki: "A piece of an article (1-2 kelime ancak) taglerken Tag Name koymaya neden gerek olsun ki, highlight edilen kısım direkt Tag Name olmayacak mı?" gibi bir yorum yapmıştı.
Cumartesi toplantıda netleştirelim.

**Comment by emrecalik** [comment]
Geribildirimin çok teşekkür ederim @active-sludge. Güncelledim.

**Comment by active-sludge** [comment]
Eline sağlık @emrecalik
