### ISSUE TITLE
Update the mockups

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#47]
This issue is related to #46 Make scenarios more specific.

- You will update the mockups, based on these scenarios. 
- A Mockup should show the exact scenario.
- Narrow scenarios if you need. 
- The customer should see the mockups and should not have any doubt about what they are seeing.
- Add hyperlinks from scenarios to mockups and vice versa. To navigate easily.
- Add a small title and text on top of each mockup to get a glance at what the customer is seeing.
- Mockups do not have to be only gif, you can add images of steps.

You can access the mockups files on the [repo](https://github.com/CAKES-coding/swe574-group2/tree/develop/wikode-Mockup).

**Comment by active-sludge** [comment]
- [ ] Scenario 1 Mockup'ındaki screen recorder'ı kaldıralım.
- [ ] Scenario 2'de bir belirsizlik var. Highlighht edilip, taglenen kısım, tag'de gözükmüyor.

Scenario 2'de bir karışıklık var gibi. Geçen hafta hoca demişti ki: "A piece of an article (1-2 kelime ancak) taglerken Tag Name koymaya neden gerek olsun ki, highlight edilen kısım direkt Tag Name olmayacak mı?" gibi bir yorum yapmıştı.
Cumartesi toplantıda netleştirelim. @jajimentol @kenankural @semihsolmaz

**Comment by active-sludge** [comment]
Mockup'larin ustune senaryolari yazalim.

**Comment by active-sludge** [comment]
Senaryo 2:
1. "the third highly pathogenic coronavirus" highlight edilir.
2. Tag aramaya "COVID-19 pandemic" yazilir.
3. "Save tags" 'e basilir.
4. Asagidaki tag listesinde 
- tag name: COVID-19 pandemic
- description: the third highly pathogenic coronavirus
- digerleri ayni.

**Comment by emrecalik** [comment]
Gerilbildirimlerin için çok teşekkürler. @active-sludge Güncelledim.

**Comment by active-sludge** [comment]
Eline sağlık @emrecalik
