### ISSUE TITLE
Add milestones

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#48]
We need to have milestones to feel the achievements, and make sure we are on the correct route.

Add meaningful milestones.
Make some of them presentable to the customer.

**Comment by active-sludge** [comment]
Aşağıdaki gibi hazırladım. Tag a piece of an article Milestone'u hocaya sunabiliriz diye düşündüm. 

https://github.com/CAKES-coding/swe574-group2/milestones

**Comment by kenankural** [comment]
Eline sağlık bence çok yerinde olmuş tarihler, istersen derste Suzan Hoca' ya deadline ile ilgili bilgi soralım, belki update etmemiz gereken tarihler olabilir. Bildiğim kadarıyla derslerin son günü 4 ocak, geçen yıldan tecrübe ettiğimiz kadarıyla 20 Ocak' a kadar vaktimiz olabilir. Notlarıma yazdım bu şekilde kapatıyorum.
