### ISSUE TITLE
Admin can not view delete user button within user list

### ISSUE THREAD

**Issue by kenankural** [CAKES-coding/swe574-group2#59]
**Describe the bug**
Admin can not view delete user button within user list

**To Reproduce**
1. Login with an admin user
2. Click on user list
3. At the right of the user list
4. Delete user button is missing

**Expected behavior**
There should be a delete button and is not applicable

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Comment by semihsolmaz** [comment]
![image](https://user-images.githubusercontent.com/25771247/141531966-2aed97ba-7fce-42c7-bc38-933382185a59.png)

solved while entrez article fetching implementation

**Comment by kenankural** [comment]
Eline sağlık @semihsolmaz
