### ISSUE TITLE
Populate Database with Articles

### ISSUE THREAD

**Issue by kenankural** [CAKES-coding/swe574-group2#60]
**Is your feature request related to a problem? Please describe.**
We can not test the features without having populated database with articles

**Describe the solution you'd like**
We need to fetch 10k articles and test the application

**Additional context**
We will parse;
* PM_id
* keywords
* authors
* abstract
* title
* journal
* publish date

**Comment by semihsolmaz** [comment]
On develop brach:
https://github.com/CAKES-coding/swe574-group2/pull/65

/wikode/getArticles/ path goes toarticle fetching screen:
1. enter topic to be searched in entrez.
2. enter a number of articles to be fetched (some article with missing data[no date, no author, no abstract] will be skipped)
![image](https://user-images.githubusercontent.com/25771247/141760182-2f0571f5-819f-476f-9f1c-ce580d9a969b.png)

**Comment by semihsolmaz** [comment]
@jajimentol uygunsa main'e tasıyabiliriz.
Sonrasında bir topic belirleyip azuredaki ortamı populate edebiliriz.

**Comment by kenankural** [comment]
@jajimentol uygunsa bunu kapatabiliriz abi

**Comment by jajimentol** [comment]
Elinize sağlık, güzel olmuş. Closed.
