### ISSUE TITLE
Define activity model to be used in user activities

### ISSUE THREAD

**Issue by kenankural** [CAKES-coding/swe574-group2#63]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem, we need activity stream in order to create suggestion page

**Describe the solution you'd like**
Model will be developed using activity stream

**Additional context**
This issue related to both research and development

**Comment by jajimentol** [comment]
[Activity Model](https://github.com/CAKES-coding/swe574-group2/wiki/Activity-Model) çalışması için wiki oluşturuldu

**Comment by emrecalik** [comment]
Eline sağlık @jajimentol. Activity type olarak "Tagging" de eklenebilir.

**Comment by jajimentol** [comment]
Activity type ları direkt olarak [Activty Strems 2.0](https://www.w3.org/TR/activitystreams-core/) dökümantasyonundan alıyoruz, o yüzden kendi type ımızı oluşturamıyoruz. Tagging aktivitesini, articlea tag eklendi şeklinde yapacağız o yüzden.
