### ISSUE TITLE
Create Activity Manager

### ISSUE THREAD

**Issue by kenankural** [CAKES-coding/swe574-group2#64]
**Is your feature request related to a problem? Please describe.**
Logging activities after related users' activities

**Describe the solution you'd like**
A method to generate activity log in activity stream 2.0 format will be created to be used in related views after actions occured.

**Additional context**
It will be used in user activities and will be feed with inputs;
* who
* when
* target
* how

**Comment by jajimentol** [comment]
id, json-ld, userid, activityType, targetId sütunları ile activity tablosu açılacak.

**Comment by jajimentol** [comment]
Closed with PR [#103](https://github.com/CAKES-coding/swe574-group2/pull/103).
