### ISSUE TITLE
Tag the whole article

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#67]
**Describe the solution you'd like**
The user shall be redirected to an article detail page.
The user shall tag the whole article.

**Comment by emrecalik** [comment]
The part of this feature was implemented in issue #61.

**Comment by emrecalik** [comment]
![tagArticle](https://user-images.githubusercontent.com/62518089/144666221-dcfce102-e6db-4b29-a89a-074f32d202a1.png)
