### ISSUE TITLE
Add examples to activity stream wiki page

### ISSUE THREAD

**Issue by semihsolmaz** [CAKES-coding/swe574-group2#73]
For further clarification add examples to activity research page (https://github.com/CAKES-coding/swe574-group2/wiki/Activity-Model).

add 2 examples in JSONLD format using wikode use cases

**Comment by jajimentol** [comment]
Added to [Activity Model](https://github.com/CAKES-coding/swe574-group2/wiki/Activity-Model)

**Comment by semihsolmaz** [comment]
[Activity Model](https://github.com/CAKES-coding/swe574-group2/wiki/Activity-Model)

sample JSONb added
