### ISSUE TITLE
Research  w3 annotation model for tagging (annotation)

### ISSUE THREAD

**Issue by semihsolmaz** [CAKES-coding/swe574-group2#74]
w3 annotation model can be considered for tagging (annotation) feature.

- Research  https://www.w3.org/TR/annotation-model/#annotations
- Create an example in jsonLD format

**Comment by kenankural** [comment]
Assignee is corrected.

**Comment by jajimentol** [comment]
Added example json-ld to [Activity Model Wiki](https://github.com/CAKES-coding/swe574-group2/wiki/Activity-Model)
