### ISSUE TITLE
Make admin do not set superuser status

### ISSUE THREAD

**Issue by semihsolmaz** [CAKES-coding/swe574-group2#85]
**Describe the bug**
While setting admin status for a new user, RelatedObjectDoesNotExist error.

**To Reproduce**
1. Go to users page
2. Click on make admin for a non admin user
3. See error

**Expected behavior**
User need to be made admin. Thus can see admin screens on next login.

**Error Log**
<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">RelatedObjectDoesNotExist at /wikode/userList/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">User has no userprofileinfo.</pre>

Request Method: | POST
-- | --
http://20.56.24.44:8000/wikode/userList/
3.2.9
RelatedObjectDoesNotExist
User has no userprofileinfo.
/usr/local/lib/python3.10/site-packages/django/db/models/fields/related_descriptors.py, line 421, in __get__
/usr/local/bin/python

</body>
</html>

**Comment by kenankural** [comment]
@semihsolmaz değişiklikleri tamamladım. PR açtım. Kontrol edebilir misin ?

**Comment by semihsolmaz** [comment]
tesekkurler.
Olmayan bir modele referans veriyormus.
