### ISSUE TITLE
Add milestone report

### ISSUE THREAD

**Issue by emrecalik** [CAKES-coding/swe574-group2#87]
Weekly milestone report will be added to wiki:

- Milestone
- Issue
- Morale
- What is done
- What will be done
- Lessons learned

**Comment by active-sludge** [comment]
Our first weekly milestone report is ready.
Please give your comments.
@semihsolmaz 

https://github.com/CAKES-coding/swe574-group2/wiki/Milestone-Report-1-(27.11.2021)

**Comment by jajimentol** [comment]
Closed.
