### ISSUE TITLE
Change cloud platform

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#92]
Azure credit is finished. 
We need to migrate to the google cloud.

**Comment by semihsolmaz** [comment]
dev server on the cloud move to GCP.
new IP:
http://34.159.77.79/8000

- CI values are updated for new VM
- new VM configured for auto deployment

**Comment by kenankural** [comment]
@semihsolmaz firewall ayarlarında bir problem olabilir mi ? Siteye ulaşılamıyor.

**Comment by semihsolmaz** [comment]
Hayır ayarlar ok siteye ulaşılabiliyor. 11-12 arası bazı GCP servislerinde problemler olmuş belki o zamana denk gelmişsindir ama yukarıdaki link su an açılıyor

**Comment by active-sludge** [comment]
Ip adresinde port'u ayiran iki nokta ust uste yanlis olmus. Asagidakini kullanabilirsiniz.
http://34.159.77.79:8000

**Comment by kenankural** [comment]
Teşekkürler, kapatıyorum.
