### ISSUE TITLE
Fetch wiki items related to the selected wiki item

### ISSUE THREAD

**Issue by emrecalik** [CAKES-coding/swe574-group2#93]
- When user selects a wiki item to tag the article, related wiki items to the selected one will be fetched and saved to database.
- These related wiki items will be used for suggestion feature.

**Comment by emrecalik** [comment]
![tag](https://user-images.githubusercontent.com/62518089/144029260-410cbd6f-6cb4-4954-b72c-210b3cec21d0.png)
![tag-inheritance](https://user-images.githubusercontent.com/62518089/144029279-a39cd6f4-f1f6-4c3f-ae3f-f37f23c2c567.png)

**Comment by emrecalik** [comment]
![tag](https://user-images.githubusercontent.com/62518089/144031623-fe5cfed9-baad-451a-89b7-689e9b09c335.png)
![tag-inheritance](https://user-images.githubusercontent.com/62518089/144031633-63c34d47-a932-4645-9e91-b6ffc4ca76ba.png)

**Comment by semihsolmaz** [comment]
Elinize sağlık. Q kodlar üzerinden wikidata entry ilişkisini sağlayabiliyoruz.
[suggestion](https://github.com/CAKES-coding/swe574-group2/milestone/10) 'da da kullaılacak
