### ISSUE TITLE
Pagination error

### ISSUE THREAD

**Issue by active-sludge** [CAKES-coding/swe574-group2#95]
**Describe the bug**
Search results do not show the second page.

```
TypeError at /wikode/
unsupported operand type(s) for +: 'NoneType' and 'str'
```

**To Reproduce**
1. Search for an article
2. Click on second page.
3. See error

**Expected behavior**
Should go to the second page

**Comment by semihsolmaz** [comment]
İlgili [PR](https://github.com/CAKES-coding/swe574-group2/pull/104)'ı linkledim.
Pagination ile arama sonuçlarında gezinirken filtre ve sıralama tercihleri korunuyor.
