### ISSUE TITLE
Histogram graph shows only 2021 articles

### ISSUE THREAD

**Issue by jajimentol** [CAKES-coding/swe574-group2#96]
**Describe the bug**
Histogram at search page is showing only 2021 articles.

**To Reproduce**
1. Go to Home
2. Search for a keyword
3. See Histogram at the top

**Expected behavior**
Histogram should show differnet years, like 2021-2020 and 2019

**Additional context**
The issue might be related to database poplation, we need to populate with a larger collection.

**Comment by jajimentol** [comment]
Database populated with 'lupus' keyword.
When searched, articles are shown from also 2019 and 2020.

**Comment by active-sludge** [comment]
I searched for covid and was able to see articles from 2018 to 2022.
