### ISSUE TITLE
Histogram value gap is less than 1

### ISSUE THREAD

**Issue by jajimentol** [CAKES-coding/swe574-group2#97]
**Describe the bug**
Hİstogram y axis values show decimal values, however the article count is always multiplier of 1
**To Reproduce**
1. Go to Home
2. Search for a keyword
3. See histogram at the top

**Expected behavior**
Histogram shall show non-decimal count numbers

**Comment by kenankural** [comment]
Changed the assignee

**Comment by active-sludge** [comment]
Tested. Working 👍
