### ISSUE TITLE
Milestone report: Lessons learned shall include Mad, Sad, Glad

### ISSUE THREAD

**Issue by jajimentol** [CAKES-coding/swe574-group2#99]
In our milestone reports, lessons learned part shall include;
-Mad: Explaining what we have decided to do, but had destuctive impacts. (Make tests in live)
-Sad: Explaining what we have decided to do, but had negative imapcts. (Prepare for demo presentation)
-Glad: Explaining what we have decided to do, and had positive impacts.

**Comment by active-sludge** [comment]
Finished the report.
Please check it out:
https://github.com/CAKES-coding/swe574-group2/wiki/Milestone-Report-2-(06.12.2021)

**Comment by kenankural** [comment]
Can ile birlikte toplantı yaptık ve Milestone raporunun üzerinden geçtik. Eline sağlık abi, kapatıyorum. .
